// <auto-generated />
using System;
using CajeroAutomatico1.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CajeroAutomatico1.Migrations
{
    [DbContext(typeof(CajeroDbContext))]
    partial class CajeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("CajeroAutomatico1.Dominio.Cliente", b =>
                {
                    b.Property<string>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Clave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CajeroAutomatico1.Dominio.Cuenta", b =>
                {
                    b.Property<int>("CuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.HasKey("CuentaId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("CajeroAutomatico1.Dominio.Transaccion", b =>
                {
                    b.Property<long>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuentaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("TransaccionId");

                    b.HasIndex("CuentaId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("CajeroAutomatico1.Dominio.Cuenta", b =>
                {
                    b.HasOne("CajeroAutomatico1.Dominio.Cliente", null)
                        .WithOne("Cuenta")
                        .HasForeignKey("CajeroAutomatico1.Dominio.Cuenta", "ClienteId");
                });

            modelBuilder.Entity("CajeroAutomatico1.Dominio.Transaccion", b =>
                {
                    b.HasOne("CajeroAutomatico1.Dominio.Cuenta", null)
                        .WithMany("Transacciones")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
